# Generated by Django 3.0.5 on 2020-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
